### PR TITLE
Syntax highlights for git diff.

### PR DESCRIPTION
**Pull request by daliusd**
You can see this diff when you enable verbose git commit messages.
See `commit.verbose` in https://git-scm.com/docs/git-config.

### CODE REVIEW

**Review by alerque — COMMENTED** [review]
Question: don't these sometimes show up as inline highlights nested inside their block level counterparts? Shouldn't they at least be a shade different (e.g. bright instead of dim) so that they show up in the event of nesting? I could be wrong about this usage, but that was my impression.

**Comment by daliusd** [comment]
I don't know answer to your question.

This is how it looks like. `s:bg` maybe is better choice so I will change it to `s:bg`. I personally don't care which one is better as both are better than previous situation.

image

**Comment by alerque** [comment]
Since writing I've been trying to replicate the scenario I thought would happen and can't, so I may have been imagining things.

**Comment by daliusd** [comment]
Here is what is in this pull request now:
image

**Comment by daliusd** [comment]
You can use ":verbose syntax" command to check what syntax highlight commands are used to highlight that file.

**Comment by alerque** [comment]
Actually comparing actual usage I think what I was suggesting is wrong. Lets back out that last "minor fix". Sorry for the run around, but I can't find the case where this matters and having different results for git diffs than normal diffs (esp. visible with a dark background) seems less than ideal.

**Review by alerque — APPROVED** [review]

**Comment by daliusd** [comment]
Good point about making it look the same. Reverted.

**Comment by alerque** [comment]
Thanks for the conribution, and sorry about the bogus early review comments ;-)

**Pull request merged**
